### ISSUE TITLE
Data inserts into topic but not in MongoDB

### ISSUE THREAD

**Issue by praveendhaked** [RADAR-CNS/RADAR-MongoDbConnector#39]
This is the log
```
INFO 2 have been processed (org.radarcns.connect.mongodb.MongoDbSinkTask:57)
INFO 0 have been written in MongoDB 0 records need to be processed. (org.radarcns.connect.mongodb.MongoDbWriter:59)
```
It happens when 
1. I started zookeeper , broker then created topic after that started mongodb sink connector, so it works fine. Let's assume i have inserted 50 documents in mongodb successfully.

2. Now i closed mongodb sink connector , broker, zookeeper for one or two days then i restarts zookeeper, broker , mongodb sink connector. Now if i insert new document to same topic then this topic inserts on 0 offset , next document on 1 offset and so on. But, our connector reads from offset 51 (cause it has written last 50 documents successfully.) So, it doesn't write in mongodb 50 records then it starts writing from 51st record and then works fine.

Please, can anyone tell me how can i reset this offset in my mongodb sink connector to zero or any other possible fix for this problem.

**Comment by yatharthranjan** [comment]
Hi @praveendhaked , the reason this happens is because the connectors stores states (offsets) within them according to the records processed from kafka. (as they are intended to continuously dump incoming records).
When you recreate kafka, the old data in kafka is deleted. But the data in MongoDB persists and hence the offsets within mongodb persist. There can be 2 mitigations.
1. You can make the data in kafka persist on disk and through restarts. This is the recommended approach.
2. If you want the data to be read from offset 0, then just delete the offset file inside MongoDB from the `OFFSETS` collection. Please take a look at this issue #33 which may provide a view of where the offset file can be found within the MongoDB. 

Hope this helps.

**Comment by yatharthranjan** [comment]
You can also try the following - 

To reset a connector running in standalone mode you have to stop it and then modify `name` and `offset.storage.file.filename` respectively inside `sink.properties` and `standalone.properties`

This is also mentioned in the [README](https://github.com/RADAR-base/MongoDb-Sink-Connector#notes)

**Comment by praveendhaked** [comment]
Hi @yatharthranjan 

I tried by just deleting OFFSETS collection but it again restores back all offsets. 

I have tried modifying name and offset.storage.file.filename respectively inside sink.properties and standalone.properties
But this didn't helped. May be because I didn't delete OFFSETS collection from mongodb.

**Comment by praveendhaked** [comment]
Hi @yatharthranjan Thanks for your help. My problem has been fixed.
The problem was because log directory and data directory for kafka broker and zookeeper were default. By  default zookeeper and broker uses /tmp directory that's why on rebooting that data and logs were wiped out. Changing those directories solved my problem.
